image: maven:3-jdk-10-slim

variables:
  MAVEN_CLI_OPTS: "--batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
  - .m2/repository/
  - target/

build:
  stage: verify
  script:
  - mvn $MAVEN_CLI_OPTS verify
