[versions]
jda = "4.2.0_222"
lavaplayer = "1.3.63"
lavaplayer-ARM = "1.3.10"
slf4J = "2.0.0-alpha1"
logback = "1.3.0-alpha4"
unirest = "3.11.04"
picocli = "4.5.2"
jackson = "2.12.0"
httpclient = "4.5.13"
lang3 = "3.11"
reflections = "0.9.12"
jump3r = "1.0.5"
emoji-java = "5.1.1"
imgscalr = "4.2"
thumbnailator = "0.4.13"
twitter4j = "4.0.7"

[dependencies]
jda = { module = "net.dv8tion", name = "JDA", version.ref = "jda" }
lavaplayer = { module = "com.sedmelluq", name = "lavaplayer", version.ref = "lavaplayer" }
lavaplayer-arm = { module = "com.github.natanbc", name = "lavaplayer-arm-natives", version.ref = "lavaplayer-arm" }
jump3r = { module = "de.sciss", name = "jump3r", version.ref = "jump3r" }
slf4j = { module = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }
logback = { module = "ch.qos.logback", name = "logback-classic", version.ref = "logback" }
unirest = { module = "com.konghq", name = "unirest-java", version.ref = "unirest" }
picocli = { module = "info.picocli", name = "picocli", version.ref = "picocli" }
jackson-core = { module = "com.fasterxml.jackson.core", name = "jackson-core", version.ref = "jackson" }
jackson-annotations = { module = "com.fasterxml.jackson.core", name = "jackson-annotations", version.ref = "jackson" }
jackson-databind = { module = "com.fasterxml.jackson.core", name = "jackson-databind", version.ref = "jackson" }
httpclient = { module = "org.apache.httpcomponents", name = "httpclient", version.ref = "httpclient" }
lang3 = { module = "org.apache.commons", name = "commons-lang3", version.ref = "lang3" }
reflections = { module = "org.reflections", name = "reflections", version.ref = "reflections" }
emoji-java = { module = "com.vdurmont", name = "emoji-java", version.ref = "emoji-java" }
imgscalr = { module = "org.imgscalr", name = "imgscalr-lib", version.ref = "imgscalr" }
thumbnailator = { module = "net.coobird", name = "thumbnailator", version.ref = "thumbnailator" }
twitter4j = { module = "org.twitter4j", name = "twitter4j-core", version.ref = "twitter4j" }

[bundles]
jackson = ["jackson-core", "jackson-annotations", "jackson-databind"]

[plugins]
com.github.johnrengelman.shadow = "6.1.0"
com.github.ben-manes.versions = "0.36.0"
io.freefair.lombok = "5.3.0"
