version: 1
update_configs:
  # Update your Gemfile (& lockfiles) as soon as
  # new versions are published to the RubyGems registry
  - package_manager: "java:gradle"
    directory: "/"
    update_schedule: "daily"
    default_reviewers:
      - "RakSrinaNa"