name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build with gradle
        uses: OrangeLabs-moe/gradle-actions@v5.0-openjdk-14
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
