name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build with gradle
        uses: MrRamych/gradle-actions/openjdk-13@3.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
