name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - uses: actions/cache@v1
        name: Restore gradle cache
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.OS }}-gradle-${{ env.cache-name }}-
            ${{ runner.OS }}-gradle-
            ${{ runner.OS }}-
      - uses: actions/cache@v1
        name: Cache gradle wrapper
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
      - name: Set wrapper permissions
        run: chmod +x gradlew
      - name: Check project
        run: ./gradlew check
        env:
          GITHUB_USER: RakSrinaNa
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker
        run: |
          echo ${{ secrets.DOCKER_PAT }} | docker login ghcr.io -u RakSrinaNa --password-stdin
          docker build . --pull --tag ghcr.io/raksrinana/rsndiscord:$GITHUB_SHA --cache-from ghcr.io/raksrinana/rsndiscord:latest
          docker push ghcr.io/raksrinana/rsndiscord:$GITHUB_SHA
        env:
          GITHUB_TOKEN: ${{ secrets.DOCKER_PAT }}
